feat: 오늘의 조합 홈 조회 API 구현
UMC5th-DrinkingGourmet/dg-BackEnd pull request #22
Opened 2024-01-16 15:34 UTC by kylo-dev

## 요약

- 오늘의 조합 API 중 홈 페이지 조회 API 구현

## 상세 내용

- Combination과 CombinationImage의 데이터를 페이징하여 DTO로 전송합니다. 

## 질문 및 이외 사항

-

## 이슈 번호

- close #21

2024-01-16 16:15 UTC, wooing1084 approved these changes
고생하셨습니다!

2024-01-17 07:34 UTC, minhyeokDev requested changes
코멘트 남긴 것들 확인 부탁드립니다! 다른 팀원들과 한번 이야기 해보는 게 좋을 것 같습니다~

2024-01-17 07:34 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +@RequestMapping("/api/combinations")
여기 /api는 빼는게 어떨까요??

2024-01-17 07:34 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +//    }
이렇게 주석 처리한 부분은 빼고 PR 올려주시는게 나을것 같습니다!
카일로 PR을 보니, 한번에 구현해서 주석처리하고 다른 PR에서 올린 것 같은데, 주석처리해서 올리는 것보단 한번에 PR을 올리거나 주석을 지워서 올리는게 충돌도 나지 않고 좋은 방향일 것 같습니다.
이렇게 되면 리뷰하기가 힘듭니다 ㅠㅠ
다른 팀원 분들도 보고 피드백 부탁드려요!

2024-01-17 07:34 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +        return ApiResponse.onSuccess(combinationQueryService.getCombinationPreviewDTOList(page));
페이징 처리도 잘해주셨네요! 이 부분은 일단 이렇게 진행하고 프론트분들과 상의하고 진행하면 될 것 같습니다!

2024-01-17 07:34 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
> +    private List<CombinationImage> combinationImages = new ArrayList<>();
여기 양방향 매핑 진행하신 이유가 있을까요?

2024-01-17 07:34 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
> +//    }
이 부분도 위와 마찬가지로 주석을 빼주시거나 하는게 어떨까요? 이렇게 되면 아마도 merge 할때 주석들이 다 쌓이게 될 것 같습니다..

2024-01-17 07:34 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
> +@RequestMapping("/api/combinations/{combinationId}/combinationLikes")
여기도 위와 마찬가지 입니다!

2024-01-17 08:18 UTC, YASICJUNWOO commented on src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
> +    private List<CombinationImage> combinationImages = new ArrayList<>();
카일로가 의도했을 지는 모르지만 Combination 조회 시 이미지 url들 한번에 보내려고 한 것 같아요!
저도 Recipe 조회 시 상기 이유로 양방향 매핑하고 순환참조에 대해서는 @JsonBackReference 사용하려고 했는데 어떻게 생각하시나요!

다른 방법은 해당 DTO 빌드 시 Image관련 Service에서 조회해서 한꺼번에 빌드할 수 있을꺼 같아요!

2024-01-17 14:35 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
> +    private List<CombinationImage> combinationImages = new ArrayList<>();
> 카일로가 의도했을 지는 모르지만 Combination 조회 시 이미지 url들 한번에 보내려고 한 것 같아요! 저도 Recipe 조회 시 상기 이유로 양방향 매핑하고 순환참조에 대해서는 @JsonBackReference 사용하려고 했는데 어떻게 생각하시나요!
> 
> 다른 방법은 해당 DTO 빌드 시 Image관련 Service에서 조회해서 한꺼번에 빌드할 수 있을꺼 같아요!

오 해당 방법 이용해보는 것도 좋을 것 같습니다!

2024-01-17 17:37 UTC, YASICJUNWOO approved these changes
고생하셨습니다!

2024-01-18 08:01 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +@RequestMapping("/api/combinations")
/api를 앞에 붙여서 구분하려는 용도로 사용했는데, 빼도 괜찮을 것 같습니다.

2024-01-18 08:03 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +//    }
저 혼자 오늘의 조합을 구현하는 게 아니라 리우랑 나눠서 구현한다고 하여 미리 controller 틀을 잡아둔 거였습니다.
앞으로는 PR를 올릴 때 주석처리는 빼고 올리겠습니다.

2024-01-18 08:03 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +        return ApiResponse.onSuccess(combinationQueryService.getCombinationPreviewDTOList(page));
감사합니다. 리우

2024-01-18 08:03 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
> +
추후에 해당 부분을 삭제하고 해시태그로 바꿔 구현하였습니다.

2024-01-18 08:13 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
> +@RequestMapping("/api/combinations{combinationId}/combinationComments")
리우 말대로, conbinationId를 사용하지 않는 API가 있을 것 같습니다.
URL을 각각 설정하는 방식으로 설정해 보겠습니다.

2024-01-18 10:09 UTC, Blue-hyeon approved these changes

2024-01-18 10:09 UTC, Blue-hyeon commented on src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
> +    private List<CombinationImage> combinationImages = new ArrayList<>();
@JsonBackReference는 저도 처음 들어봤는데, 활용하는 거 좋은 것 같아요! 해당 방법에 대해 저도 찾아보겠습니다.

2024-01-21 05:04 UTC, minhyeokDev approved these changes

2024-01-21 15:01 UTC, merged