feat: 오늘의 조합 상세 정보 조회 API
UMC5th-DrinkingGourmet/dg-BackEnd pull request #24
Opened 2024-01-16 15:49 UTC by kylo-dev

Related: #23

## 요약

- 오늘의 조합 상세 정보 조회 API 구현

## 상세 내용

- Combination, CombinationImage, CombinationComment 정보 조회
- CombinationComment는 페이징하여 전

## 질문 및 이외 사항

**ex) 프론트에게 응답하는 DTO**

```javascript

{
  "combination": {
    "combinationId": 1,
    "combinationName": "String",
    "combinationInfo": "String",
    "cookingTime": "String",
    "calorie": "String",
    "likeCount": 10,
    "ingredient": "String",
    "recipeInstruction": "String",
    "images": [
      {
        "imageId": 1,
        "imageUrl": "String"
      },
      {
        "imageId": 2,
        "imageUrl": "String"
      }
    ],
	},
	"member": {
		"memberId": 1,
    "memberName": "String",
    "profileImageUrl": "String"
	},
  "combinationComment": {
    "listSize": 10,
    "totalPage": 3,
    "totalElements": 25,
    "isFirst": false,
    "isLast": true
	  "combinationCommentList": [
    {
      "combinationCommentId": 1,
      "content": "String",
      "parentId": null
    },
    {
      "combinationCommentId": 2,
      "content": "String",
      "parentId": 1
    },
    // ... 댓글 정보 계속 추가
	  ]
	}
}
```

## 이슈 번호

- close #23

2024-01-16 18:10 UTC, wooing1084 approved these changes
고생하셨습니다!

2024-01-17 07:51 UTC, minhyeokDev requested changes
전체적으로 앞선 PR과 겹치는 내용과 더불어 dto 분리 및 댓글 조회 API 분리에 대한 내용을 코멘트로 작성해놓았습니다! 확인 부탁드립니다.
또한 지금은 상세조회시 해시태그가 보이지 않는 것 같은데 맞나요?

2024-01-17 07:51 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +//    }
여기도 이전 리뷰와 마찬가지 입니다! 해당 부분을 일단 merge하고 다 끝나면 주석들을 삭제할지, 아니면 커밋해서 주석처리를 삭제하고 반영할지 이야기 해봅시다!

2024-01-17 07:51 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
> +    }
지금 이 부분들은 전 PR과 겹치는 부분들이네요,, 다음번부턴 기능별로 끊어서 커밋하고, 한번에 모든 PR 보단 한 API마다 PR 올리는 게 충돌도 피하고 리뷰하기 편할 것 같습니다!

2024-01-17 07:51 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
> +    }
이 부분은 Member의 dto로 옮겨야할 것 같습니다!

2024-01-17 07:51 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
> +    }
여기도 마찬가지로 CombinationComment 의 dto로 빼야할것 같습니다.

2024-01-17 07:51 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
> +        return toCombinationDetailDTO(combinationResult, memberResult, combinationCommentResult);
제 생각에는 댓글 조회 API를 분리하는게 나을 것 같습니다.
현재 오늘의 조합 상세 조회시 Combination 내용과 Member 관련 내용을 넘겨주고, Comment 관련은 분리하는게 나을 것 같은데 다른 분들 생각과 프론트 분들과 상의해야할 것 같네요!

2024-01-18 08:20 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
> +    }
넵, 도메인 별로 구분해서 다시 올리겠습니다.

2024-01-18 08:21 UTC, kylo-dev commented
> 전체적으로 앞선 PR과 겹치는 내용과 더불어 dto 분리 및 댓글 조회 API 분리에 대한 내용을 코멘트로 작성해놓았습니다! 확인 부탁드립니다. 또한 지금은 상세조회시 해시태그가 보이지 않는 것 같은데 맞나요?

해시태그 부분을 누락해서 추후에 해시태그가 조회 되도록 수정하였습니다.

2024-01-18 08:24 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
> +    }
맞는 것 같습니다. 추후에 Merge 할 때 충돌이 덜 생기기 위해서 API 마다 PR을 올리도록 하겠습니다.

2024-01-18 08:24 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
> +    }
수정하겠습니다.

2024-01-18 08:26 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
> +        return toCombinationDetailDTO(combinationResult, memberResult, combinationCommentResult);
저번에 PM께 물어봤을 때, 댓글 데이터도 한꺼번에 전달해 달라고 하셔서 같이 전달해서 작성하였습니다.
추후에 프론트 분들과 상의 후 수정하겠습니다.

2024-01-18 10:13 UTC, Blue-hyeon approved these changes

2024-01-18 10:13 UTC, Blue-hyeon commented on src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
> +        return toCombinationDetailDTO(combinationResult, memberResult, combinationCommentResult);
한꺼번에 전달할 경우에는 저도 같이 넘겨주는 게 좋을 것 같은데, 해당 부분에 대해서 월요일날 회의하면 좋을 것 같습니다 .

2024-01-21 05:04 UTC, minhyeokDev approved these changes

2024-01-21 10:54 UTC, YASICJUNWOO approved these changes
피드백 반영 고생하셨습니다 ☺️

2024-01-21 15:02 UTC, minhyeokDev approved these changes

2024-01-21 15:25 UTC, merged