feat: 오늘의 조합 작성 API 구현
UMC5th-DrinkingGourmet/dg-BackEnd pull request #31
Opened 2024-01-16 16:27 UTC by kylo-dev

Related: #30

## 요약

- 오늘의 조합을 작성하는 API 입니다.

## 상세 내용

- Combination, HashTag, HashTagOption, CombinationImage 엔티티의 데이터를 사용하여 오늘의 조합을 작성합니다.
- S3 서비스를 이용하여 다중 이미지를 처리하였습니다.
- 중복된 HashTag가 아닌 기존의 HashTag를 사용합니다.

## 질문 및 이외 사항

-

## 이슈 번호

- close #30

2024-01-16 18:30 UTC, wooing1084 approved these changes
고생하셨습니다!

2024-01-17 08:12 UTC, minhyeokDev requested changes
수고하셨습니다! 코멘트 한 부분들 확인 부탁드리고, 전체적으로 PR 내용이 너무 겹치게 될것 같아서 앞으로 PR에만 주의해주시면 될 것 같습니다.
또한 코멘트에도 마찬가지로 오늘의 조합에는 추천 받은 주류 추천이 필요 없는 것으로 알고 있습니다. 이 부분도 코멘트 부탁드립니다!

2024-01-17 08:12 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/Combination.java
> +
이 부분은 앞선 PR이랑 충돌날 것 같네요..ㅠㅠ

2024-01-17 08:12 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +    }
오늘의 조합에선 추천받은 조합이 필요없다고 알고 있습니다! 이 부분 확인 부탁드립니다!

2024-01-17 08:12 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
> +        }
이미지 관한 로직은 CombinationImage 도메인단에서 처리하는게 나을 것 같은데, 일단 이 방법으로 잘 작동한다면 이대로 구현하고 추후에 리팩토링 하는 것도 괜찮을 것 같습니다!

2024-01-18 08:57 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
> +        }
이미지를 생성하는 부분을 이미지 서비스를 통해 구현하는 방향으로 수정하겠습니다.

2024-01-18 08:58 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
> +    }
![image](https://github.com/UMC5th-DrinkingGourmet/dg-BackEnd/assets/103489352/ed49b72b-b2bf-4270-8a1d-17031ad80c0c)

제가 알기로는 오늘의 조합을 작성하기 위해서는 사전에 GPT를 통해 추천 받은 조합들 중에서 하나를 선택하고 작성하는 것으로 알고 있어 진행했습니다.

**"오늘의 조합 작성 API"** 부분을 개발하면서 생각하다가 필요할 것 같다고 생각이 들어 구현하였습니다.

해당 부분을 삭제하거나 우잉에게 전달하겠습니다.

2024-01-18 10:35 UTC, Blue-hyeon approved these changes
카일로 열일로 ㅋㅋㅋ 고생하셨습니다!!!!!!!1 카일로 짱!!!!!!!!!!!!

2024-01-18 12:15 UTC, YASICJUNWOO approved these changes
고생하셨습니다!! ☺️

2024-01-21 05:05 UTC, minhyeokDev approved these changes

2024-01-21 15:47 UTC, merged