Feat: 주류 추천 정보 입력 구현
UMC5th-DrinkingGourmet/dg-BackEnd pull request #32
Opened 2024-01-16 18:02 UTC by wooing1084

Related: #28 

## 요약

- 주류 추천에 사용할 사용자 정보 입력 API입니다.

## 상세 내용

- Member 엔티티의 주류 추천 관련 데이터를 PATCH합니다.

## 질문 및 이외 사항

- 현재 소셜 로그인이 develop에 merge되지 않아 헤더를 통해 사용자 정보를 얻을 수 없기 때문에 임시적으로 Request parameter에 입력하도록 하였습니다. 소셜 로그인 merge되는 대로 수정될 예정입니다.

## 이슈 번호

- close #28

2024-01-17 04:28 UTC, kylo-dev reviewed
고생했어요! 우잉

2024-01-17 08:19 UTC, minhyeokDev requested changes
수고하셨습니다! 코멘트 확인 부탁드립니다!

2024-01-17 08:19 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/member/Member.java
> +@Setter
Setter는 편하긴 하지만 어떤 목적과 의미로 수정되는 지 파악하기 어렵기 때문에 사용을 지양합니다 ㅠㅠ
대신 목적이 명확하게 보이도록 메서드 이름을 지어서 Setter 대신 사용하는 걸 추천드립니다!

2024-01-17 08:19 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/member/dto/MemberRequestDTO.java
> +public class MemberRequestDTO {
이 부분은 카일로는 CombinationRequest, Response 이런 식으로 작성했는데 이부분은 통일이 필요해보이네요!
서버 회의 때 정하도록 하겠습니다.

2024-01-17 08:19 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
> +    public ApiResponse<MemberResponseDTO.RecommendInfoDTO> patchRecommendInfo(Long memberID, @RequestBody MemberRequestDTO.RecommendInfoDTO recommendInfoDTO){
memberId가 RequestParam으로 받고 있지 않는 것 같습니다! 확인 부탁드립니다~

2024-01-18 03:23 UTC, minhyeokDev approved these changes
수고하셨습니다! 빠른 반영 감사합니다~

2024-01-18 04:18 UTC, YASICJUNWOO approved these changes
고생하셨습니다 😄

2024-01-18 09:02 UTC, kylo-dev approved these changes

2024-01-18 10:24 UTC, Blue-hyeon approved these changes

2024-01-18 15:40 UTC, merged