Feat : 레시피 기본 설정 및 전체 조회 API
UMC5th-DrinkingGourmet/dg-BackEnd pull request #35
Opened 2024-01-17 17:32 UTC by YASICJUNWOO

## 요약

- Recipe 도메인 기본 설정과 전체 Recipe 조회 API

## 상세 내용

- 기본적인 DTO 추가하였습니다
- 레시피 + 작성자 이름 조합으로 Param 받아서 Recipe 구분하기 위해 VO 사용하였습니다.
- 전체 조회는 삭제가 되지 않은 Recipe들 만 조회하기 위해 state가 true인 Recipe들 만 조회하였습니다.
<img width="947" alt="image" src="https://github.com/UMC5th-DrinkingGourmet/dg-BackEnd/assets/99794552/334a1b29-8a8c-429e-ac6a-08261d62f4ff">

## 질문 및 이외 사항

- API 요청시 RecipeId를 사용하는 게 보안 상의 이슈로 사용하지 않는데,
현재 레시피 이름은 중복이 가능해서 구분하기 위해 (레시피 + 작성자 이름) 조합으로 Param을 받아서 사용하려고 합니다.
이 방식이 비효율적이라고 생각해서 의견있으시면 부탁드려요!
일단은 이 방식대로 구현한 다음 리팩토링 과정에서 바꿔야 할 것 같습니다!

- 디렉토리 구조도 의견 부탁드려요!

## 이슈 번호

- close #12

2024-01-18 08:47 UTC, minhyeokDev requested changes
수고하셨습니다! 코멘트 한번만 확인 부탁드립니다!
저도 메이슨한테 많이 배우네요..!!
일단 저희 프로젝트에서 컨버터는 사용하지 않고 Service를 Service / ServiceImpl로 분리해서 작업하는 정도로만 하기로 했습니다!
일단 레시피 담당은 메이슨이라서 일단 이렇게 하고 추후에 수정해도 될 것 같습니다!

2024-01-18 08:47 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/recipe/converter/RecipeConverter.java
> +    }
앗 저희 프로젝트에서 컨버터는 사용하지 않고 Service를 Service / ServiceImpl로 분리해서 작업하는 정도로만 하기로 했습니다! 혹시 그 회의때 메이슨이 참가하지 못했던 회의였을 수 도 있네요 ㅠㅠ
일단 레시피 담당은 메이슨이라서 일단 이렇게 하고 추후에 수정해도 될 것 같습니다!

2024-01-18 08:47 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeParamVO.java
> +    }
오 name과 memberName으로 받으면 확실히 구별은 가능하겠네요!
그런데 혹시 ios 같은 어플에서도 url이 노출될 위험이 있어서 RecipeId 를 사용하지 않는 건가요?
관련한 자료가 있으면 저도 확인하고 싶습니다! 부탁드려도 될까요?
RecipeId 와 쿼리문 한번 비교해보면 좋을 것 같습니다!
이 방법 말고는 저도 지금은 떠오르지 않아서 한번 고민해보겠습니다 ㅠㅠ

2024-01-18 08:47 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequestDTO.java
> +public class RecipeRequestDTO {
RecipeRequest로 이름 통일하면 좋을 것 같습니다! 아래 Response도 마찬가지입니다 ㅎㅎ 이거 회의때 정했어야 했는데 미리 말 못해드려 죄송합니다 ㅠ

2024-01-18 08:47 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
> +    }
이 메소드에서도 @Transactional이 필요한가요?? 잘 몰라서 여쭤봅니다!

2024-01-18 08:47 UTC, minhyeokDev commented on src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
오류 추가 굿입니다!👍

2024-01-18 10:32 UTC, Blue-hyeon commented on src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
> +    }
앗 저도 이부분 궁금합니다! 저는 보통 transactional을 Service 클래스에만 붙여왔었는데, DTO에도 Transactional을 붙이는 이유가 따로 있을까요??

2024-01-18 10:39 UTC, YASICJUNWOO commented on src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeParamVO.java
> +    }
저도 앱이라서 고민을 많이했는데 상용화 전까지는 효율성을 봐서라도  id 정도는 허용해도 괜찮지 않을까 합니다!
이 부분 수정하고 추후 문제가 될 때 다시 논의해보면 될 것 같습니다!!

2024-01-18 10:39 UTC, YASICJUNWOO commented on src/main/java/com/example/dgbackend/domain/recipe/converter/RecipeConverter.java
> +    }
앗 정보 전달 감사합니다! converter 관련 부분 수정해서 다시 pr 올려놓겠습니다! 😄

2024-01-18 10:39 UTC, YASICJUNWOO commented on src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequestDTO.java
> +public class RecipeRequestDTO {
넵 감사합니다~!!

2024-01-18 10:41 UTC, YASICJUNWOO commented on src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
> +    }
이 부분은 습관성 복붙때문에 들어간 것 같습니다ㅜㅜ 수정해놓겠습니다 리뷰 감사드려요!! 😄

2024-01-18 16:57 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
> +    }
java 람다식을 잘 적용한 것 같아 코드를 보면서 많이 배웁니다. 메이슨
고생하셨습니다.

2024-01-18 16:59 UTC, kylo-dev approved these changes

2024-01-19 08:45 UTC, minhyeokDev approved these changes
빠른 반영 감사합니다! 수고하셨습니다!! 👍👍

2024-01-19 11:50 UTC, wooing1084 approved these changes
고생하셨습니다!

2024-01-22 10:15 UTC, Blue-hyeon approved these changes

2024-01-22 10:22 UTC, wooing1084 approved these changes

2024-01-22 11:04 UTC, merged