Feat: 주류 추천 API
UMC5th-DrinkingGourmet/dg-BackEnd pull request #61
Opened 2024-01-24 08:11 UTC by wooing1084

## 요약
- 주류 추천 API

## 상세 내용
- Client에서 주류추천 정보 입력 후 요청시 GPT API로 주류 추천하는 API입니다.
- API 버전은 GPT-3.5-turbo, Dall-e-2 사용하였습니다.

### 구현한 API
(POST) /recommends/request

## Postman 결과
- 추천 요청 API
![스크린샷 2024-01-24 오후 5 04 57](https://github.com/UMC5th-DrinkingGourmet/dg-BackEnd/assets/32007781/a4e3449f-1585-459c-8556-805d74cb14c2)

## 질문 및 이외 사항
- 이미지 크기는 현재 1024x1024인데 더 줄여야 하는지 키워야 하는지 논의가 필요할거같습니다.
- 성능 개선 필요
- 이미지 생성 성능 개선 필요(Dall-e-2 -> Dall-e-3 및 프롬프트 엔지니어링)

## 이슈 번호

close #17

2024-01-24 09:41 UTC, minhyeokDev requested changes
수고하셨습니다! 코멘트 확인 부탁드립니다.
너무 잘해주셨는데 전반적인 API 흐름을 간단하게라도 적어주시면 이해하는데 있어서 큰 도움이 될 것 같습니다!
예시 이미지는 어떻게 나오는 지도 궁금하네요!

2024-01-24 11:21 UTC, wooing1084 commented on src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
> +        return ApiResponse.onSuccess(response);
아 원래 이미지 생성하는 부분이 밑에 들어갔었어서 저렇게 했는데, 통합하면서 까먹고 안 바꿔놨네요 바꿔놓겠습니다!

2024-01-24 11:22 UTC, wooing1084 commented on src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
> +//        String reason = content.split("\n")[1];
아 아래부분은 이젠 사용되지 않는 코드인데 지우는걸 깜빡했습니다. 수정후 커밋하겠습니다!

2024-01-24 13:46 UTC, kylo-dev reviewed
GPT 프롬프트 구현하느라 고생했어요. 우잉

2024-01-24 13:46 UTC, kylo-dev commented on src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
> +            throw new ApiException(ErrorStatus._NULL_FOOD_NAME);
데이터 관련 정보는 Service에서 처리하여 Controller와 역할을 분리하면 좋을 것 같아요. 
고생했어요 우잉.

2024-01-24 13:46 UTC, kylo-dev approved these changes

2024-01-25 15:19 UTC, minhyeokDev approved these changes
수고하셨습니다~!

2024-01-28 13:37 UTC, Blue-hyeon approved these changes
챗지피티 조련사. 정.우.잉

2024-01-28 13:46 UTC, merged